/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110645-gd4c48ee7f3-20230517"
#endif /* AVUTIL_FFVERSION_H */
